# Generated by Django 6.0.3 on 2026-03-23 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('metodo_solicitado', models.CharField(choices=[('auto', 'Automático'), ('promedio', 'Promedio'), ('linear', 'Linear'), ('arima', 'ARIMA'), ('sarima', 'SARIMA'), ('prophet', 'Prophet')], default='auto', max_length=20)),
                ('metodo_usado', models.CharField(max_length=20)),
                ('inflacion_anual', models.FloatField(default=0.04)),
                ('variacion_costos', models.FloatField(default=0.03)),
                ('meses_historicos', models.IntegerField()),
                ('score_confiabilidad', models.CharField(max_length=20)),
                ('pnl_mensual_json', models.JSONField(default=dict)),
                ('pnl_anual_json', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
