# Generated by Django 6.0.3 on 2026-03-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='analisis_ia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='historial_json',
            field=models.JSONField(default=dict),
        ),
    ]
