# Generated by Django 6.0.3 on 2026-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_proyecto_analisis_ia_proyecto_historial_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='incremento_salarial',
            field=models.FloatField(default=0.05),
        ),
    ]
